spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?sslmode=disable
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      data-locations: classpath:insert_users.sql
      continue-on-error: false

api:
  version: v1

# swagger = http://{host}:{port}/{api.version}/credibanco/swagger-ui/index.html
springdoc:
  swagger-ui:
    path: /${api.version}/credibanco/

server:
  port: ${SERVER_PORT:1010}