spring:
  datasource:
    url: jdbc:sqlserver://${DB_HOST}:${DB_PORT};databaseName=${DB_DATABASE};encrypt=true;trustServerCertificate=true;
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update

api:
  version: v1

# swagger = http://{host}:{port}/{api.version}/credibanco/swagger-ui/index.html
springdoc:
  swagger-ui:
    path: /${api.version}/credibanco/

server:
  port: ${SERVER_PORT}


