services:
  credibanco:
    build:
      context: ../
      dockerfile: docker-compose/Dockerfile
    image: gustavo0426/api-credibanco-postgres:latest
    container_name: api-credibanco
    restart: always
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - credibanco_network
    depends_on:
      - credibanco-db

  credibanco-db:
    image: postgres:16-alpine
    container_name: db-credibanco
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - credibanco_network
      - shared_pgadmin_network
    volumes:
      - credibanco_postgres_data:/var/lib/postgresql/data

networks:
  credibanco_network:
    name: credibanco_network
    driver: bridge
  shared_pgadmin_network:
    external: true

volumes:
  credibanco_postgres_data:
    name: credibanco_postgres_data