services:
  credibanco:
    build:
      context: ../
      dockerfile: docker-compose/Dockerfile
    image: gustavo0426/credibanco-api-postgres:latest
    container_name: credibanco-api
    restart: always
    environment:
      DB_USERNAME: ${DATABASE_USERNAME}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_DATABASE: ${DATABASE_NAME}
      DB_HOST: ${DATABASE_HOST}
      DB_PORT: ${DATABASE_PORT}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - "9091:${SERVER_PORT}"
    networks:
      - credibanco_network
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:16-alpine
    container_name: credibanco-db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    networks:
      - credibanco_network
      - shared_pgadmin_network
    volumes:
      - credibanco_postgres_data:/var/lib/postgresql/data

networks:
  credibanco_network:
    name: credibanco_network
    driver: bridge
  shared_pgadmin_network:
    external: true

volumes:
  credibanco_postgres_data: