services:
  credibanco:
    build:
      context: ../
      dockerfile: credibanco/Dockerfile
    image: gustavo0426/credibanco-api:latest
    container_name: credibanco-api
    restart: always
    environment:
      DB_USERNAME: ${DATABASE_USERNAME}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_DATABASE: ${DATABASE_NAME}
      DB_HOST: ${DATABASE_HOST}
      DB_PORT: ${DATABASE_PORT}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - "9091:${SERVER_PORT}"
    networks:
      - network
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:16-alpine
    container_name: credibanco-db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5433:5432"
    networks:
      - network
      - shared_pgadmin_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  network:
  shared_pgadmin_network:
    external: true
volumes:
  postgres_data: